2024-01-12 17:40:04,000 ERROR frappe Could not take error snapshot: characters_written
Site: train.com
Form Dict: {'doctype': 'Train Doc', 'with_parent': '1', 'cached_timestamp': '', 'cmd': 'frappe.desk.form.load.getdoctype'}
Traceback (most recent call last):
  File "/home/hevin/hevin/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/hevin/hevin/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/hevin/hevin/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/hevin/hevin/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/hevin/hevin/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/hevin/hevin/apps/frappe/frappe/desk/form/load.py", line 72, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/hevin/hevin/apps/frappe/frappe/desk/form/load.py", line 83, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/hevin/hevin/apps/frappe/frappe/desk/form/meta.py", line 44, in get_meta
    meta = FormMeta(doctype)
  File "/home/hevin/hevin/apps/frappe/frappe/desk/form/meta.py", line 55, in __init__
    self.load_assets()
  File "/home/hevin/hevin/apps/frappe/frappe/desk/form/meta.py", line 65, in load_assets
    self.add_code()
  File "/home/hevin/hevin/apps/frappe/frappe/desk/form/meta.py", line 120, in add_code
    self.add_html_templates(path)
  File "/home/hevin/hevin/apps/frappe/frappe/desk/form/meta.py", line 135, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/hevin/hevin/apps/newdemo/newdemo/newdemo/doctype/train_doc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hevin/hevin/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/hevin/hevin/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
